package com.gd.termcounter.term;

import java.util.HashSet;
import java.util.Set;

public class Exclusions {
    public static Set<String> excludedWords = new HashSet<>() {{
        add("and");
        add("a");
        add("the");
        add("to");
        add("of");
        add("in");
        add("our");
        add("with");
        add("you");
        add("for");
        add("we");
        add("software");
        add("will");
        add("are");
        add("on");
        add("be");
        add("is");
        add("an");
        add("working");
        add("as");
        add("development");
        add("work");
        add("your");
        add("that");
        add("have");
        add("by");
        add("team");
        add("from");
        add("this");
        add("which");
        add("using");
        add("can");
        add("if");
        add("part");
        add("all");
        add("within");
        add("their");
        add("also");
        add("or");
        add("at");
        add("-");
        add("experience");
        add("more");
        add("&");
        add("other");
        add("new");
        add("help");
        add("code");
        add("people");
        add("one");
        add("but");
    }};
}
